apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-k8s-demo
  template:
    metadata:
      labels:
        app: jenkins-k8s-demo
    spec:
      containers:
        - name: jenkins-k8s-demo
          image: jenkins-k8s-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: BUILD_NUMBER
              value: "1"