apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-demo-service
spec:
  selector:
    app: jenkins-k8s-demo
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080